### ISSUE TITLE
查询商品的上下架状态函数url错误

### ISSUE THREAD

**Issue by Wzitang** [xiaoyukarl/jd_biz#1]
ProductRequest::saleStatus内获取了getFullUrl,并用$url调用queryApi. 导致请求错误

**Comment by jkaltopp** [comment]
我也出现了这个问题

**Comment by xiaoyukarl** [comment]
> ProductRequest::saleStatus内获取了getFullUrl,并用$url调用queryApi. 导致请求错误

是的，这里多写了一个getFullUrl，现在已修复

**Comment by xiaoyukarl** [comment]
> 我也出现了这个问题

已修复

**Comment by xiaoyukarl** [comment]
fixed
